CREATE DATABASE IF NOT EXISTS cadastrophp
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE cadastrophp;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(140) NOT NULL,
    email VARCHAR(140) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
